from flask import session

from project.models import *
from project.db import get_item

DummyBasket = Basket()

def get_user():
    user_dict = session.get('user')
    if user_dict:
        user = UserInfo(
            id=user_dict['id'],
            username=user_dict['username'],
            email=user_dict['email'],
            phone=user_dict['phone'],
            role=user_dict['role']
        )
    return user

def get_basket():
    basket_data = session.get('basket')
    basket = Basket()
    # we need to convert the basket items from dicts to BasketItem objects
    # this is a bit of a hack, but it works for now
    if isinstance(basket_data, dict):
        for item in basket_data.get('items', []):
            basket.add_item(
                BasketItem(item['id'],
                get_item(item['product']['id']),
                item['quantity'])
            )
    return basket

def _save_basket_to_session(basket):
    session['basket'] = {
        'items': [
            {
                'id': item.id,
                'quantity': item.quantity,
                'tour': {
                    'id': item.tour.id
                }
            } for item in basket.items
        ]
    }

def add_to_basket(item_id, quantity=1):
    basket = get_basket()
    basket.add_item(BasketItem(item_id, get_item(item_id), quantity))
    # now store/update the basket in the session
    _save_basket_to_session(basket)

def remove_from_basket(basket_item_id):
    basket = get_basket()
    basket.remove_item(basket_item_id)
    # now store/update the basket in the session
    _save_basket_to_session(basket)

def empty_basket():
    session['basket'] = DummyBasket

def convert_basket_to_order(basket):
    # convert the basket to an order
    order = Order(
        id = None,  # this should be generated by the database
        status = OrderStatus.PENDING,
        user = get_user(),
        total_cost= basket.total_cost(),
        items = basket.items,
    )
    return order