from flask import session

from project.models import *
from project.db import DummyUserInfo, get_product

DummyBasket = Basket()

def get_user():
    return session.get('user', DummyUserInfo)

def get_basket():
    basket =  session.get('basket', DummyBasket)
    # we need to convert the basket items from dicts to BasketItem objects
    # this is a bit of a hack, but it works for now
    if isinstance(basket, dict):
        tmp = Basket()
        for item in basket.get('items', []):
            tmp.add_item(
                BasketItem(item['id'],
                get_product(item['product']['id']),
                item['quantity'])
            )
        basket = tmp
    return basket

def add_to_basket(product_id, quantity=1):
    basket = get_basket()
    basket.add_item(BasketItem(product_id, get_product(product_id), quantity))
    # now store/update the basket in the session
    session['basket'] = basket

def remove_from_basket(basket_item_id):
    basket = get_basket()
    basket.remove_item(basket_item_id)
    # now store/update the basket in the session
    session['basket'] = basket

def empty_basket():
    session['basket'] = DummyBasket

def convert_basket_to_order(basket):
    # convert the basket to an order
    order = Order(
        id = 'order_1',  # this should be generated by the database
        status = OrderStatus.PENDING,
        user = get_user(),
        total_cost= basket.total_cost(),
        items = basket.items,
    )
    return order